version: '3.8'

networks:
  webapp:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: client
    image: node:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www/html/vue
      - /var/www/html/vue/node_modules
    networks:
      - webapp
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
    ports:
      - "8000:8000"
    depends_on:
      - "database"
    networks:
      - webapp

  database:
    image: mysql:8.0.15
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_survey
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD:
    ports:
      - 3307:3306
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - webapp
volumes:
  mysql_data: